package dialogs;

import common.Tools;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;

public class Manual extends JFrame {
    private JScrollPane contentPane;
    private JTextPane textPane1;

    public Manual() {
        setContentPane(contentPane);
    }

    public static void start() {
        Manual dialog = new Manual();
        StyledDocument doc = dialog.textPane1.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        dialog.textPane1.setContentType("text/html");
        try {
            dialog.textPane1.setText (new String (Tools.extractResource("manual.html")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        dialog.textPane1.setEditable(false);

        dialog.pack();
        //dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JScrollPane();
        contentPane.setMinimumSize(new Dimension(350, 500));
        contentPane.setPreferredSize(new Dimension(350, 500));
        textPane1 = new JTextPane();
        contentPane.setViewportView(textPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
