package dialogs;

import common.Tools;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;

public class Manual extends JFrame {
    private JPanel contentPane;
    private JButton dismissButton;
    private JTextPane textPane1;

    public Manual() {
        setContentPane(contentPane);
        getRootPane().setDefaultButton(dismissButton);
        dismissButton.addActionListener(e -> dispose());
    }

    public static void start() {
        Manual dialog = new Manual();
        StyledDocument doc = dialog.textPane1.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        dialog.textPane1.setContentType("text/html");
        dialog.loadPage("manual.html");
        dialog.textPane1.setEditable(false);

        dialog.pack();
        //dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }


    private void loadPage(String name) {
        try {
            textPane1.setText (new String (Tools.extractResource("manual.html")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        textPane1.setCaretPosition(0);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setMinimumSize(new Dimension(350, 500));
        contentPane.setPreferredSize(new Dimension(350, 500));
        dismissButton = new JButton();
        dismissButton.setText("Dismiss");
        contentPane.add(dismissButton, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMinimumSize(new Dimension(400, 500));
        scrollPane1.setPreferredSize(new Dimension(400, 500));
        contentPane.add(scrollPane1, BorderLayout.CENTER);
        textPane1 = new JTextPane();
        scrollPane1.setViewportView(textPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
